import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
Link;
import headerStyles from "./header.module.css";
const inter = Inter({ subsets: ["latin"] });
import footerStyles from "./footer.module.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className={headerStyles.header}>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/posts">Posts</Link>
          </nav>
        </header>
        {children}
        <footer className={footerStyles.footer}>
          <p>Made By JK</p>
          <p>&copy;2024</p>
          <p>CO/TechEducators</p>
        </footer>
      </body>
    </html>
  );
}
