import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
Link;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
        </nav>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
